services:
  site:
    build: .
    volumes:
      - .:/site
    ports:
      - "4000:4000"
      - "35729:35729"  # for livereload
    environment:
      - JEKYLL_ENV=development
    command: bundle exec jekyll serve --host 0.0.0.0 --watch --livereload
